public with sharing class testApex {
    public testApex() {
        if(true){
            
            
            System.debug('test');
        }
        
        
        if(true){
            
                          System.debug('test');
        }
    if(true){
        System.
        debug('test');
        }
    }
    public void testA(){
        final String x = '12312321312321312312312321321321321321312' + 'abcasdadsadsadassasasasa1231';
        final String y = 
        
        '12312321312321312312312321321321321321312' + 'abcasdadsadsadassasasasa1231' + x;
        System.debug(x);
        System.debug(y);
    }
}
